blueprint:
  name: Z2M - Philips Hue Dimmer (RWL021) - Device trigger mapping
  description: Map all Philips Hue dimmer button actions (on/up/down/off press/hold/release) via Zigbee2MQTT device triggers.
  domain: automation

  input:
    remote:
      name: Remote device
      selector:
        device:

    on_press:
      name: on_press
      default: []
      selector: { action: {} }
    on_press_release:
      name: on_press_release
      default: []
      selector: { action: {} }
    on_hold:
      name: on_hold
      default: []
      selector: { action: {} }
    on_hold_release:
      name: on_hold_release
      default: []
      selector: { action: {} }

    up_press:
      name: up_press
      default: []
      selector: { action: {} }
    up_press_release:
      name: up_press_release
      default: []
      selector: { action: {} }
    up_hold:
      name: up_hold
      default: []
      selector: { action: {} }
    up_hold_release:
      name: up_hold_release
      default: []
      selector: { action: {} }

    down_press:
      name: down_press
      default: []
      selector: { action: {} }
    down_press_release:
      name: down_press_release
      default: []
      selector: { action: {} }
    down_hold:
      name: down_hold
      default: []
      selector: { action: {} }
    down_hold_release:
      name: down_hold_release
      default: []
      selector: { action: {} }

    off_press:
      name: off_press
      default: []
      selector: { action: {} }
    off_press_release:
      name: off_press_release
      default: []
      selector: { action: {} }
    off_hold:
      name: off_hold
      default: []
      selector: { action: {} }
    off_hold_release:
      name: off_hold_release
      default: []
      selector: { action: {} }

mode: single

trigger:
  - platform: device
    domain: mqtt
    device_id: !input remote
    type: action
    subtype: on_press
    id: on_press
  - platform: device
    domain: mqtt
    device_id: !input remote
    type: action
    subtype: on_press_release
    id: on_press_release
  - platform: device
    domain: mqtt
    device_id: !input remote
    type: action
    subtype: on_hold
    id: on_hold
  - platform: device
    domain: mqtt
    device_id: !input remote
    type: action
    subtype: on_hold_release
    id: on_hold_release

  - platform: device
    domain: mqtt
    device_id: !input remote
    type: action
    subtype: up_press
    id: up_press
  - platform: device
    domain: mqtt
    device_id: !input remote
    type: action
    subtype: up_press_release
    id: up_press_release
  - platform: device
    domain: mqtt
    device_id: !input remote
    type: action
    subtype: up_hold
    id: up_hold
  - platform: device
    domain: mqtt
    device_id: !input remote
    type: action
    subtype: up_hold_release
    id: up_hold_release

  - platform: device
    domain: mqtt
    device_id: !input remote
    type: action
    subtype: down_press
    id: down_press
  - platform: device
    domain: mqtt
    device_id: !input remote
    type: action
    subtype: down_press_release
    id: down_press_release
  - platform: device
    domain: mqtt
    device_id: !input remote
    type: action
    subtype: down_hold
    id: down_hold
  - platform: device
    domain: mqtt
    device_id: !input remote
    type: action
    subtype: down_hold_release
    id: down_hold_release

  - platform: device
    domain: mqtt
    device_id: !input remote
    type: action
    subtype: off_press
    id: off_press
  - platform: device
    domain: mqtt
    device_id: !input remote
    type: action
    subtype: off_press_release
    id: off_press_release
  - platform: device
    domain: mqtt
    device_id: !input remote
    type: action
    subtype: off_hold
    id: off_hold
  - platform: device
    domain: mqtt
    device_id: !input remote
    type: action
    subtype: off_hold_release
    id: off_hold_release

action:
  - choose:
      - conditions: "{{ trigger.id == 'on_press' }}"
        sequence: !input on_press
      - conditions: "{{ trigger.id == 'on_press_release' }}"
        sequence: !input on_press_release
      - conditions: "{{ trigger.id == 'on_hold' }}"
        sequence: !input on_hold
      - conditions: "{{ trigger.id == 'on_hold_release' }}"
        sequence: !input on_hold_release

      - conditions: "{{ trigger.id == 'up_press' }}"
        sequence: !input up_press
      - conditions: "{{ trigger.id == 'up_press_release' }}"
        sequence: !input up_press_release
      - conditions: "{{ trigger.id == 'up_hold' }}"
        sequence: !input up_hold
      - conditions: "{{ trigger.id == 'up_hold_release' }}"
        sequence: !input up_hold_release

      - conditions: "{{ trigger.id == 'down_press' }}"
        sequence: !input down_press
      - conditions: "{{ trigger.id == 'down_press_release' }}"
        sequence: !input down_press_release
      - conditions: "{{ trigger.id == 'down_hold' }}"
        sequence: !input down_hold
      - conditions: "{{ trigger.id == 'down_hold_release' }}"
        sequence: !input down_hold_release

      - conditions: "{{ trigger.id == 'off_press' }}"
        sequence: !input off_press
      - conditions: "{{ trigger.id == 'off_press_release' }}"
        sequence: !input off_press_release
      - conditions: "{{ trigger.id == 'off_hold' }}"
        sequence: !input off_hold
      - conditions: "{{ trigger.id == 'off_hold_release' }}"
        sequence: !input off_hold_release
    default: []
