blueprint:
  name: Z2M - Hue Dimmer (RWL021) - Lights + smooth dim on hold
  description: >
    For Philips Hue Dimmer RWL021 (Zigbee2MQTT). Map on/off press actions, and do smooth
    brightness ramp on up/down hold (stop on release).
  domain: automation

  input:
    remote:
      name: Remote device
      selector:
        device:

    light_target:
      name: Light (or group) to control
      selector:
        target:
          entity:
            domain: light

    # What to do on normal presses (optional; defaults provided)
    on_press_action:
      name: On press action (optional)
      description: What to do when ON is pressed.
      default: []
      selector:
        action: {}

    off_press_action:
      name: Off press action (optional)
      description: What to do when OFF is pressed.
      default: []
      selector:
        action: {}

    # Smooth dim settings
    step_pct:
      name: Brightness step (%)
      description: Smaller = smoother/slower. Typical 2–6.
      default: 4
      selector:
        number:
          min: 1
          max: 20
          step: 1
          mode: slider

    interval_ms:
      name: Step interval (ms)
      description: Lower = smoother/faster updates. Typical 120–250.
      default: 150
      selector:
        number:
          min: 80
          max: 500
          step: 10
          mode: slider

mode: restart

trigger:
  - platform: device
    domain: mqtt
    device_id: !input remote
    type: action
    subtype: on_press
    id: on_press

  - platform: device
    domain: mqtt
    device_id: !input remote
    type: action
    subtype: off_press
    id: off_press

  - platform: device
    domain: mqtt
    device_id: !input remote
    type: action
    subtype: up_hold
    id: up_hold

  - platform: device
    domain: mqtt
    device_id: !input remote
    type: action
    subtype: down_hold
    id: down_hold

  # Stop on release
  - platform: device
    domain: mqtt
    device_id: !input remote
    type: action
    subtype: up_hold_release
    id: stop
  - platform: device
    domain: mqtt
    device_id: !input remote
    type: action
    subtype: down_hold_release
    id: stop

  # Optional: also stop on press_release events
  - platform: device
    domain: mqtt
    device_id: !input remote
    type: action
    subtype: up_press_release
    id: stop
  - platform: device
    domain: mqtt
    device_id: !input remote
    type: action
    subtype: down_press_release
    id: stop

variables:
  step_pct: !input step_pct
  interval_ms: !input interval_ms
  light_target: !input light_target

action:
  - choose:
      # STOP branch
      - conditions: "{{ trigger.id == 'stop' }}"
        sequence:
          - stop: "released"

      # ON press
      - conditions: "{{ trigger.id == 'on_press' }}"
        sequence:
          - choose:
              - conditions: "{{ (on_press_action | default([])) | length > 0 }}"
                sequence: !input on_press_action
            default:
              - service: light.turn_on
                target: !input light_target

      # OFF press
      - conditions: "{{ trigger.id == 'off_press' }}"
        sequence:
          - choose:
              - conditions: "{{ (off_press_action | default([])) | length > 0 }}"
                sequence: !input off_press_action
            default:
              - service: light.turn_off
                target: !input light_target

      # Smooth DIM UP while holding
      - conditions: "{{ trigger.id == 'up_hold' }}"
        sequence:
          - repeat:
              while:
                - condition: template
                  value_template: "{{ true }}"
              sequence:
                - service: light.turn_on
                  target: !input light_target
                  data:
                    brightness_step_pct: "{{ step_pct }}"
                    transition: 0
                - delay:
                    milliseconds: "{{ interval_ms }}"

      # Smooth DIM DOWN while holding
      - conditions: "{{ trigger.id == 'down_hold' }}"
        sequence:
          - repeat:
              while:
                - condition: template
                  value_template: "{{ true }}"
              sequence:
                - service: light.turn_on
                  target: !input light_target
                  data:
                    brightness_step_pct: "{{ -step_pct }}"
                    transition: 0
                - delay:
                    milliseconds: "{{ interval_ms }}"
    default: []
